version: 2.1
orbs:
  node: circleci/node@7.1.0

jobs:
  test_and_preview:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build package
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn pkg-pr-new publish --compact --packageManager=yarn
          name: Publish preview release
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_preview:
    jobs:
      - test_and_preview
